search_queries:
  - "High-level overview of intelligent user interfaces and their impact on modern UI/UX design"
  - "Latest advancements in AI-driven user interfaces and practical applications in 2024"
  - "Best practices for designing AI-enhanced user interfaces in mobile apps"
  - "Tools and frameworks for building intelligent user interfaces: A 2024 guide"

specific_questions:
  - "What are the latest trends in intelligent user interfaces, and how are they shaping user experience?"
  - "How can deep learning be integrated into UI design to create more intuitive and adaptive user experiences?"
  - "What are the best practices for ensuring accessibility and inclusivity in AI-powered user interfaces?"
  - "How do intelligent user interfaces utilize user data for personalization while maintaining privacy and ethical standards?"


platforms: #   Available: [youtube, github, google]
  - google
time_horizon: 185  # Recommended: [month = 30, quarter = 90, year = 365, 3 years = 1096]
max_outputs_per_platform: 5 # Recommended: [3, 4, 5, 6, 7, 8, 9]
output_dir: './runs'
